spring:
  application:
    name: payout-worker
  data:
    redis:
      host: localhost
      port: 6301
  kafka:
    bootstrap-servers: localhost:9401

fake-bank:
  base-url: ${FAKE_BANK_BASE_URL:http://localhost:8103}

server:
  port: 8102

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-components: always
