spring:
  application:
    name: fake-bank
  datasource:
    url: jdbc:postgresql://localhost:5403/bank
    username: bank
    password: bank
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8103

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-components: always
