spring:
  application:
    name: payout-platform
  datasource:
    url: jdbc:postgresql://localhost:5401/payout
    username: payout
    password: payout
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9401

server:
  port: 8101

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-components: always
